FROM golang:1.26.1-alpine

RUN apk add --no-cache git make gcc musl-dev

# Фиксируем версию Air, которая работает на Go 1.24
RUN go install github.com/air-verse/air@v1.52.3

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air"]