FROM golang:1.26.1-alpine

RUN apk add --no-cache git make gcc musl-dev
RUN go install github.com/air-verse/air@v1.52.3

WORKDIR /app

# Додаємо цю змінну
ENV GOFLAGS="-buildvcs=false"

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air"]