// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/postgres/cart_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "ecommers/internal/domin"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockCartRepository) AddItem(ctx context.Context, userID uuid.UUID, item *models.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, userID, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockCartRepositoryMockRecorder) AddItem(ctx, userID, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockCartRepository)(nil).AddItem), ctx, userID, item)
}

// ClearCart mocks base method.
func (m *MockCartRepository) ClearCart(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCart", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCart indicates an expected call of ClearCart.
func (mr *MockCartRepositoryMockRecorder) ClearCart(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCart", reflect.TypeOf((*MockCartRepository)(nil).ClearCart), ctx, userID)
}

// DeleteItemByUser mocks base method.
func (m *MockCartRepository) DeleteItemByUser(ctx context.Context, userID, productID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItemByUser", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItemByUser indicates an expected call of DeleteItemByUser.
func (mr *MockCartRepositoryMockRecorder) DeleteItemByUser(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItemByUser", reflect.TypeOf((*MockCartRepository)(nil).DeleteItemByUser), ctx, userID, productID)
}

// GetCartByUserID mocks base method.
func (m *MockCartRepository) GetCartByUserID(ctx context.Context, userID uuid.UUID) (*models.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByUserID", ctx, userID)
	ret0, _ := ret[0].(*models.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByUserID indicates an expected call of GetCartByUserID.
func (mr *MockCartRepositoryMockRecorder) GetCartByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByUserID", reflect.TypeOf((*MockCartRepository)(nil).GetCartByUserID), ctx, userID)
}

// GetItemByUserAndProduct mocks base method.
func (m *MockCartRepository) GetItemByUserAndProduct(ctx context.Context, userID, productID uuid.UUID) (*models.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByUserAndProduct", ctx, userID, productID)
	ret0, _ := ret[0].(*models.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByUserAndProduct indicates an expected call of GetItemByUserAndProduct.
func (mr *MockCartRepositoryMockRecorder) GetItemByUserAndProduct(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByUserAndProduct", reflect.TypeOf((*MockCartRepository)(nil).GetItemByUserAndProduct), ctx, userID, productID)
}

// UpdateItemByUser mocks base method.
func (m *MockCartRepository) UpdateItemByUser(ctx context.Context, userID, productID uuid.UUID, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemByUser", ctx, userID, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemByUser indicates an expected call of UpdateItemByUser.
func (mr *MockCartRepositoryMockRecorder) UpdateItemByUser(ctx, userID, productID, quantity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemByUser", reflect.TypeOf((*MockCartRepository)(nil).UpdateItemByUser), ctx, userID, productID, quantity)
}
